services:
  - type: web
    name: stashly-backend
    env: node
    buildCommand: yarn && yarn build
    startCommand: yarn start
    repo: https://github.com/vivekcore/Stashly
    branch: master
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: USER_SECRET_KEY
        sync: false
      - key: SALTROUND
        value: "10"